version: '3.7'

services:
  backend:
    image: appwrite/appwrite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./appwrite:/usr/src/code/appwrite:rw
    entrypoint: 'uninstall'